---
settings:
  name: BlueXP software updates
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: Documents relatifs aux mises à jour de logiciels BlueXP 
    url: "/index.html"
  - section: release-notes
  - section: get-started
  - section: ontap
  - section: support
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
