---
sidebar: sidebar 
permalink: ONTAP/update-storage-system.html 
keywords: update ontap storage system 
summary: Mettez à jour votre système de stockage ONTAP pour bénéficier des nouvelles fonctionnalités et des améliorations apportées. 
---
= Lancez la mise à jour ONTAP à l'aide des mises à jour du logiciel BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une fois que vous avez identifié la version cible de ONTAP, corrigé et validé tous les bloqueurs, vous pouvez à présent lancer la mise à jour de votre système de stockage ONTAP.

.Rôle BlueXP requis :
Administrateur d'organisation, administrateur de dossier ou de projet, administrateur de stockage ou spécialiste de l'état du système. link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Découvrez les rôles d’accès BlueXP."^]

.Étapes
. Dans le menu de navigation de gauche de BlueXP , sélectionnez *Santé > mises à jour logicielles*.
+
La liste des clusters qui nécessitent une mise à jour logicielle s'affiche.

. Identifiez la version cible ONTAP de votre système de stockage. Pour plus d'informations sur l'identification de la version cible ONTAP, reportez-vous à la section link:../ONTAP/choose-ontap-910-later.html["Comparez les versions de ONTAP pour comprendre les avantages et les risques liés aux mises à jour de logiciels BlueXP "].
. Corrigez et validez les bloqueurs ONTAP. Pour plus d'informations sur la résolution des bloqueurs, reportez-vous à la section link:../ONTAP/fix-blockers-warnings.html["Corrigez tous les bloqueurs à l'aide des mises à jour du logiciel BlueXP  avant une mise à niveau ONTAP"].
. Lisez et acceptez le contrat de licence de l'utilisateur final.
+
Attendez que l'image ONTAP soit récupérée.

. Cliquez sur *installer la mise à jour* pour terminer le processus de mise à jour.

