---
sidebar: sidebar 
permalink: get-started/prerequisites-ontap-update.html 
keywords: prerequisites for ontap update, ontap update requirements, ontap update versions, prepare for ontap update 
summary: Vérifiez les conditions requises avant de procéder à la mise à jour de ONTAP. 
---
= Préparez la mise à jour de ONTAP à l'aide des mises à jour du logiciel BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez vérifier les conditions préalables et requises avant de procéder à la mise à jour de ONTAP. Vous pouvez utiliser les mises à jour du logiciel BlueXP  pour vérifier que votre environnement opérationnel, votre connexion, votre accès au réseau et votre navigateur Web sont opérationnels.

.Rôle BlueXP requis :
Administrateur d'organisation, administrateur de dossier ou de projet, administrateur de stockage, visualiseur de stockage ou spécialiste de l'état du système. link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Découvrez les rôles d’accès BlueXP."^]

Pour utiliser les mises à jour logicielles BlueXP , vous devez vous assurer que votre environnement répond à toutes les exigences.

* Un environnement de travail est configuré dans BlueXP .
* Les informations d'identification de l'administrateur sont disponibles pour le cluster souhaité lors de la mise à jour du logiciel.
* Tous les nœuds du cluster envoient des données AutoSupport.
* Tous les nœuds doivent s'exécuter sur ONTAP 9.10 ou une version ultérieure.
* Les nœuds ne doivent pas se trouver dans une configuration MetroCluster.

