---
sidebar: sidebar 
permalink: get-started/prerequisites-ontap-update.html 
keywords: prerequisites for ontap update, ontap update requirements, ontap update versions 
summary: Vérifiez les conditions requises avant de procéder à la mise à jour de ONTAP. 
---
= Conditions requises pour mettre à jour ONTAP à l'aide des mises à jour du logiciel BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Commencez par vérifier que votre environnement opérationnel, votre connexion, votre accès au réseau et votre navigateur Web sont opérationnels.

Pour utiliser les mises à jour logicielles BlueXP , vous devez vous assurer que votre environnement répond à toutes les exigences.

* Un compte BlueXP  valide doit être disponible.
* L'environnement de travail est configuré dans BlueXP .
* Les Privileges d'administration sont disponibles pour effectuer la mise à jour du logiciel à l'aide de System Manager.
* Les informations d'identification de l'administrateur sont disponibles pour le cluster souhaité lors de la mise à jour du logiciel.
* Tous les nœuds du cluster envoient des données AutoSupport.
* Tous les nœuds doivent s'exécuter sur ONTAP 9.10 ou une version ultérieure.
* Les nœuds ne doivent pas se trouver dans une configuration MetroCluster.

