---
sidebar: sidebar 
permalink: get-started/software-updates-faq.html 
keywords: ontap update faq, ontap update frequently asked questions, software updates faq, software updates frequently asked questions 
summary: Consultez les réponses aux questions fréquemment posées sur les mises à jour du logiciel BlueXP . 
---
= Forum aux questions sur les mises à jour du logiciel BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cette FAQ peut vous aider si vous cherchez juste une réponse rapide à une question.

*Quelle est l'URL des mises à jour du logiciel BlueXP  ?*

Pour l'URL, dans un navigateur, entrez : https://console.bluexp.netapp.com/["https://console.bluexp.netapp.com/"^] pour accéder à la console BlueXP .

*Avez-vous besoin d'une licence pour utiliser les mises à jour du logiciel BlueXP  ?*

Aucun fichier de licence NetApp n'est requis.

*Pourquoi ne puis-je pas afficher le cluster dans l'onglet Historique même après la mise à jour de la version ONTAP du cluster ?*

Il faut entre 2 et 3 heures pour que le cluster apparaisse dans l'onglet History. Une fois la version ONTAP du cluster mise à jour, AutoSupport est généré. Il faut entre 2 et 3 heures pour traiter les données AutoSupport et refléter la dernière version de ONTAP.

*Pourquoi l'ancienne version de ONTAP est-elle disponible dans le tableau de bord des mises à jour logicielles, même après la mise à jour de la version ONTAP du cluster ?*

Il faut entre 2 et 3 heures pour que le cluster apparaisse dans l'onglet History. Une fois la version ONTAP du cluster mise à jour, AutoSupport est généré. Il faut entre 2 et 3 heures pour traiter les données AutoSupport et refléter la dernière version de ONTAP.

*Pourquoi est-ce que je vois différents écrans pour différentes mises à jour?*

Cela est dû à la version actuelle de ONTAP et à l'indisponibilité du connecteur BlueXP  pour les clusters. Un connecteur BlueXP  exécute la mise à jour ONTAP dans BlueXP  et ne nécessite pas de quitter BlueXP  pour une mise à jour. Pour plus d'informations sur le processus de mise à jour ONTAP pour les différentes versions de ONTAP, reportez-vous à la section link:https://docs.netapp.com/us-en/bluexp-software-updates/get-started/software-updates.html["Systèmes ONTAP pris en charge"].

*Que dois-je faire pour découvrir des clusters?*

Pour effectuer une mise à jour ONTAP pour le cluster souhaité, vous devez disposer de l'adresse IP de cluster ONTAP et des informations d'identification d'administration pour la connexion au cluster. Dans le cadre de la détection de cluster, vous devez fournir ces détails pour que la mise à jour ONTAP puisse être exécutée automatiquement.
