---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: 'software updates, ontap update, what"s new, enhancements' 
summary: Découvrez les nouvelles fonctionnalités et les améliorations apportées aux mises à jour logicielles BlueXP . 
---
= Nouveautés des mises à jour du logiciel BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Découvrez les nouveautés des mises à jour du logiciel BlueXP .



== 12 mai 2025



=== Rôle d'accès BlueXP requis

Vous devez désormais disposer de l'un des rôles d'accès suivants pour installer les mises à jour logicielles : *Administrateur de l'organisation*, *Administrateur de dossier ou de projet*, *Administrateur du stockage*, *Observateur du stockage* ou *Spécialiste de l'intégrité du stockage*. Les utilisateurs disposant du rôle d'observateur du stockage disposent de diverses autorisations liées aux mises à jour logicielles, mais ne peuvent pas les installer. link:https://docs.netapp.com/us-en/bluexp/concept-iam-predefined-roles.html["Découvrez les rôles d’accès BlueXP."^]



== 02 avril 2025



=== Risques atténués

Dans la section récapitulative des mises à jour logicielles BlueXP , vous pouvez maintenant afficher le nombre total de risques pouvant être atténués par la mise à jour du système d'exploitation. Cela permet aux utilisateurs d'évaluer les améliorations de sécurité et de stabilité de leur base d'installation.



== 07 août 2024



=== Mise à jour ONTAP

Le service de mises à jour logicielles BlueXP  offre aux utilisateurs une expérience de mise à jour fluide en limitant les risques et en leur permettant d'exploiter pleinement les fonctionnalités ONTAP.

En savoir plus sur link:https://docs.netapp.com/us-en/bluexp-software-updates/get-started/software-updates.html["Mises à jour du logiciel BlueXP "].
